### ISSUE TITLE
rsr::get_answers_list crashes R session

### ISSUE THREAD

**Issue by jborden** [sysrev/rsr#13]
running 
```{r}
rsr::get_answers_list(87659)
```
crashes the R session in R studio on my machine.

**Comment by tomlue** [comment]
looks like the jsonparse package has some issues. I'll switch back to jsonlite. Maybe try this in the future https://symbolixau.github.io/jsonify/index.html

**Comment by jborden** [comment]
I'm still having an issue with 5e62bc34 install

```
> project_id
[1] 87659
> rsr::get_answers_list(project_id)
Error in `mutate_cols()`:
! Problem with `mutate()` column `answer`.
ℹ `answer = srtidy_answer(.data$answer, .data$value_type)`.
ℹ `answer` must be size 70 or 1, not 60.
ℹ The error occurred in group 2: lid = "4c66488c-c9fd-496b-8c2e-2121eb618b43".
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by tomlue** [comment]
ok, this looks like a different issue, at least no more crashing. I will look.
