### ISSUE TITLE
cannot get my token to work

### ISSUE THREAD

**Issue by behrica** [sysrev/rsr#22]
I copied the "API token" from my user settings of the project I just created.

![image](https://user-images.githubusercontent.com/127361/193311008-42e4da33-997a-43f2-a70a-804f9763a812.png)

and I should have all permissions:

![image](https://user-images.githubusercontent.com/127361/193310384-210f4c1a-30c7-4ecf-91ad-5b52583c4695.png)

Project url is : https://sysrev.com/u/8407/p/120262

I did set it like

```r
Sys.setenv(SYSREV_TOKEN="<my api token>)
```
but any call to the api fails with

```
rsr::get_sroptions(pid=120262)
Error in `srplumber()`:
! request error
✖ Unauthorized Token
ℹ See https://r.sysrev.com
Run `rlang::last_error()` to see where the error occurred.
```

What can there be wrong ?

**Comment by tomlue** [comment]
This is an issue on the sysrev side and it is being addressed now. The service should be available again in the next 1-2 days. Thank you for making an issue here!

**Comment by tomlue** [comment]
We have updated the service and your request should now function. Please let me know if your error persists, thank you.
